import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
      >
        <header className="border-b border-[var(--accent)] bg-[var(--panel)]">
          <div className="max-w-6xl mx-auto flex items-center gap-4 p-4">
            <img
              src="/drakninja-logo.png"
              alt="DrakNinja logo: stylized ninja symbol representing the anime news platform"
              className="h-10 w-auto"
            />
            <h1 className="text-xl font-bold tracking-wide text-[var(--accent)]">
              DrakNinja News
            </h1>
          </div>
        </header>
        <main className="max-w-6xl mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}